// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADTt2R8e4DjJcqMWlNgWhfT2zctn0GSCw',
    appId: '1:78315821008:web:ec76e59101fc5fb0900bd5',
    messagingSenderId: '78315821008',
    projectId: 'haru-ssu',
    authDomain: 'haru-ssu.firebaseapp.com',
    storageBucket: 'haru-ssu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRzK7JvQPrOIcIJ96-9K4_YFaCPblMGz4',
    appId: '1:78315821008:android:a666b1d83d51c2e8900bd5',
    messagingSenderId: '78315821008',
    projectId: 'haru-ssu',
    storageBucket: 'haru-ssu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU_bsMobG2QFpO7716OrvvJxRuXajsyEc',
    appId: '1:78315821008:ios:44348af5e3250bb4900bd5',
    messagingSenderId: '78315821008',
    projectId: 'haru-ssu',
    storageBucket: 'haru-ssu.appspot.com',
    iosClientId: '78315821008-b6kueudcn4uhu113mohou0eislsfejih.apps.googleusercontent.com',
    iosBundleId: 'com.example.haru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU_bsMobG2QFpO7716OrvvJxRuXajsyEc',
    appId: '1:78315821008:ios:44348af5e3250bb4900bd5',
    messagingSenderId: '78315821008',
    projectId: 'haru-ssu',
    storageBucket: 'haru-ssu.appspot.com',
    iosClientId: '78315821008-b6kueudcn4uhu113mohou0eislsfejih.apps.googleusercontent.com',
    iosBundleId: 'com.example.haru',
  );
}
